## Processing the dataset

In [20]:
import uuid
def uuid3(data):
    return (uuid.uuid3(uuid.NAMESPACE_DNS, str(data["model"])+"-"+str(data["year"])+"-"+str(data["price"])+"-"+str(data["mileage"])+"-"+str(data["fuelType"])+"-"+str(data["mpg"])+"-"+str(data["engineSize"])))

In [21]:
import os
import string
import pandas as pd
directory = os.walk(r"archive")

data_merged = pd.DataFrame()
for path,dir_list,file_list in directory:  
    for file_name in file_list:
        file_path = os.path.join(path, file_name)
        data = pd.read_csv(file_path, sep=",")
        data.insert(0, 'brand', file_name[:-4])
        data_merged = pd.concat([data_merged,data],axis=0)
        data_merged = data_merged.reset_index(drop=True)
data_merged["uuid"] = data_merged.apply(uuid3, axis=1)
first_column = data_merged.pop('uuid')
data_merged.insert(0, 'uuid', first_column)

data_merged = data_merged.drop(['tax'],axis=1)
data_merged = data_merged.drop(['tax(Â£)'],axis=1)
data_merged["model"] = data_merged["model"].apply(lambda x: x.strip())
data_merged.insert(data_merged.shape[1], 'viewed', 0)
data_merged.insert(data_merged.shape[1], 'stared', 0)
print(data_merged)
data_merged.to_csv("used_cars.csv", sep=",", index=None)

                                       uuid brand model  year  price  \
0      8f423cf1-9c38-3c01-b86e-1caaef71327e  audi    A1  2017  12500
1      21769194-fc4e-35c9-984a-a4b8c8bc6d1f  audi    A6  2016  16500
2      53ab2768-8bf5-3d1d-9537-da2d75f311ca  audi    A1  2016  11000
3      2844f71f-3ae2-3aea-bb3d-11f742846d07  audi    A4  2017  16800
4      6c199b10-19ff-3420-b7d4-231c0682268c  audi    A3  2019  17300
...                                     ...   ...   ...   ...    ...
99182  0fc149d1-0590-3444-93b5-51b14843bbaf    vw   Eos  2012   5990
99183  0f17eabb-c33f-30a9-ae11-e0a6367cda21    vw   Fox  2008   1799
99184  c796c0db-0192-3acb-9ced-12862bd9f1b9    vw   Fox  2009   1590
99185  63d7900f-1297-3aba-9ee0-a06dbbadc13b    vw   Fox  2006   1250
99186  120767f1-0d0d-3c6b-abef-d8a0e6bcbcbb    vw   Fox  2007   2295

      transmission  mileage fuelType   mpg  engineSize  viewed  stared
0           Manual    15735   Petrol  55.4         1.4       0       0
1        Automatic    36203   Diesel  64.2         2.0       0       0
2           Manual    29946   Petrol  55.4         1.4       0       0
3        Automatic    25952   Diesel  67.3         2.0       0       0
4           Manual     1998   Petrol  49.6         1.0       0       0
...            ...      ...      ...   ...         ...     ...     ...
99182       Manual    74000   Diesel  58.9         2.0       0       0
99183       Manual    88102   Petrol  46.3         1.2       0       0
99184       Manual    70000   Petrol  42.0         1.4       0       0
99185       Manual    82704   Petrol  46.3         1.2       0       0
99186       Manual    74000   Petrol  46.3         1.2       0       0

[99187 rows x 12 columns]

In [22]:
data_dummies = data_merged.copy()
data_dummies["brand_model"] = data_merged["brand"] + data_merged["model"]

data_dummies = data_dummies.drop("model", axis=1)
data_dummies = data_dummies.drop("brand", axis=1)
print(data_merged)
data_dummies = pd.get_dummies(data_dummies, columns=["brand_model", "transmission", "fuelType"])
data_dummies = data_dummies.drop("uuid", axis=1)
data_dummies

                                       uuid brand model  year  price  \
0      8f423cf1-9c38-3c01-b86e-1caaef71327e  audi    A1  2017  12500
1      21769194-fc4e-35c9-984a-a4b8c8bc6d1f  audi    A6  2016  16500
2      53ab2768-8bf5-3d1d-9537-da2d75f311ca  audi    A1  2016  11000
3      2844f71f-3ae2-3aea-bb3d-11f742846d07  audi    A4  2017  16800
4      6c199b10-19ff-3420-b7d4-231c0682268c  audi    A3  2019  17300
...                                     ...   ...   ...   ...    ...
99182  0fc149d1-0590-3444-93b5-51b14843bbaf    vw   Eos  2012   5990
99183  0f17eabb-c33f-30a9-ae11-e0a6367cda21    vw   Fox  2008   1799
99184  c796c0db-0192-3acb-9ced-12862bd9f1b9    vw   Fox  2009   1590
99185  63d7900f-1297-3aba-9ee0-a06dbbadc13b    vw   Fox  2006   1250
99186  120767f1-0d0d-3c6b-abef-d8a0e6bcbcbb    vw   Fox  2007   2295

      transmission  mileage fuelType   mpg  engineSize  viewed  stared
0           Manual    15735   Petrol  55.4         1.4       0       0
1        Automatic    36203   Diesel  64.2         2.0       0       0
2           Manual    29946   Petrol  55.4         1.4       0       0
3        Automatic    25952   Diesel  67.3         2.0       0       0
4           Manual     1998   Petrol  49.6         1.0       0       0
...            ...      ...      ...   ...         ...     ...     ...
99182       Manual    74000   Diesel  58.9         2.0       0       0
99183       Manual    88102   Petrol  46.3         1.2       0       0
99184       Manual    70000   Petrol  42.0         1.4       0       0
99185       Manual    82704   Petrol  46.3         1.2       0       0
99186       Manual    74000   Petrol  46.3         1.2       0       0

[99187 rows x 12 columns]

,year,price,mileage,mpg,engineSize,viewed,stared,brand_model_audiA1,brand_model_audiA2,brand_model_audiA3,...,brand_model_vwUp,transmission_Automatic,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,12500,15735,55.4,1.4,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
1,2016,16500,36203,64.2,2.0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
2,2016,11000,29946,55.4,1.4,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
3,2017,16800,25952,67.3,2.0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
4,2019,17300,1998,49.6,1.0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99182,2012,5990,74000,58.9,2.0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
99183,2008,1799,88102,46.3,1.2,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
99184,2009,1590,70000,42.0,1.4,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
99185,2006,1250,82704,46.3,1.2,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
99186,2007,2295,74000,46.3,1.2,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

## AutoEncoder Recommendation

In [23]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Dense
def encoder(x):
    x = Dense(units=128, activation='relu')(x)
    x = Dense(units=64, activation='relu')(x)
    return x

def decoder(x):
    x = Dense(units=128, activation='relu')(x)
    x = Dense(units=10, activation='sigmoid')(x)
    return x
x = Input(shape=(10,))
z = encoder(x)
x_recon = decoder(z)

autoencoder = Model(inputs=x, outputs=x_recon)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

## PCA Recommendation

In [24]:
def recommend(item_id=0, num_recommendation=10):
    """
    A simple recommender system using PCA
    """
    feature_vectors = pca.fit_transform(data_dummies)
    distances = np.sum((feature_vectors - feature_vectors[item_id, :])**2, axis=1)
    print(distances)
    rec_ids = np.argsort(distances)[1:1+num_recommendation]
    rec_desc = data_merged.loc[rec_ids].to_numpy()
    print('You have viewed:\n')
    print(f'Id: {item_id} | Product: {data_merged.iloc[item_id]}')
    print('\n\nWe recommend:\n')
    for i, d in zip(rec_ids, rec_desc):
        print(f'Id: {i} | Product: {d[:]}')

In [25]:
import numpy as np
np.any(np.isnan(data_dummies))
data_dummies = pd.DataFrame(data_dummies)
data_dummies.fillna(0, inplace=True)

In [26]:
from sklearn.decomposition import PCA
from matplotlib import pyplot as plt
from sklearn import preprocessing

scaler = preprocessing.StandardScaler()
data_dummies = scaler.fit_transform(data_dummies)
pca = PCA(n_components=2)
data_dummies = pca.fit_transform(data_dummies)
print(data_dummies)
data_merged.insert(data_merged.shape[1], 'pca_1', data_dummies[:,0])
data_merged.insert(data_merged.shape[1], 'pca_2', data_dummies[:,1])
print(data_merged)
recommend(0)

[[-1.79716358 -0.59966116]
 [ 2.15772321  2.08929352]
 [-1.92707244 -0.06020747]
 ...
 [-3.14147682  3.75025667]
 [-3.48253074  4.69235748]
 [-3.3802799   4.28336184]]
                                       uuid brand model  year  price  \
0      8f423cf1-9c38-3c01-b86e-1caaef71327e  audi    A1  2017  12500
1      21769194-fc4e-35c9-984a-a4b8c8bc6d1f  audi    A6  2016  16500
2      53ab2768-8bf5-3d1d-9537-da2d75f311ca  audi    A1  2016  11000
3      2844f71f-3ae2-3aea-bb3d-11f742846d07  audi    A4  2017  16800
4      6c199b10-19ff-3420-b7d4-231c0682268c  audi    A3  2019  17300
...                                     ...   ...   ...   ...    ...
99182  0fc149d1-0590-3444-93b5-51b14843bbaf    vw   Eos  2012   5990
99183  0f17eabb-c33f-30a9-ae11-e0a6367cda21    vw   Fox  2008   1799
99184  c796c0db-0192-3acb-9ced-12862bd9f1b9    vw   Fox  2009   1590
99185  63d7900f-1297-3aba-9ee0-a06dbbadc13b    vw   Fox  2006   1250
99186  120767f1-0d0d-3c6b-abef-d8a0e6bcbcbb    vw   Fox  2007   2295

      transmission  mileage fuelType   mpg  engineSize  viewed  stared  \
0           Manual    15735   Petrol  55.4         1.4       0       0
1        Automatic    36203   Diesel  64.2         2.0       0       0
2           Manual    29946   Petrol  55.4         1.4       0       0
3        Automatic    25952   Diesel  67.3         2.0       0       0
4           Manual     1998   Petrol  49.6         1.0       0       0
...            ...      ...      ...   ...         ...     ...     ...
99182       Manual    74000   Diesel  58.9         2.0       0       0
99183       Manual    88102   Petrol  46.3         1.2       0       0
99184       Manual    70000   Petrol  42.0         1.4       0       0
99185       Manual    82704   Petrol  46.3         1.2       0       0
99186       Manual    74000   Petrol  46.3         1.2       0       0

          pca_1     pca_2
0     -1.797164 -0.599661
1      2.157723  2.089294
2     -1.927072 -0.060207
3      1.889545  1.464777
4     -1.459369 -1.390474
...         ...       ...
99182 -0.565547  5.014024
99183 -3.379156  4.404912
99184 -3.141477  3.750257
99185 -3.482531  4.692357
99186 -3.380280  4.283362

[99187 rows x 14 columns]
[ 0.         22.87160676  0.30788659 ... 20.72896323 30.84592368
 26.35017087]
You have viewed:

Id: 0 | Product: uuid            8f423cf1-9c38-3c01-b86e-1caaef71327e
brand                                           audi
model                                             A1
year                                            2017
price                                          12500
transmission                                  Manual
mileage                                        15735
fuelType                                      Petrol
mpg                                             55.4
engineSize                                       1.4
viewed                                             0
stared                                             0
pca_1                                      -1.797164
pca_2                                      -0.599661
Name: 0, dtype: object


We recommend:

Id: 9831 | Product: [UUID('b6e0bd11-49b1-3d11-8582-c36911cc0785') 'audi' 'A1' 2017 12495
 'Manual' 16000 'Petrol' 55.4 1.4 0 0 -1.7978344018965702
 -0.5938616446502419]
Id: 81122 | Product: [UUID('bc3bcb84-7fc9-395a-97ad-fa8ba2df221d') 'vauxhall' 'Zafira' 2017
 12999 'Manual' 23243 'Petrol' 41.5 1.4 0 0 -1.7881767951038718
 -0.5958250494864443]
Id: 74403 | Product: [UUID('1bdd6240-2282-3ac6-a8dd-e29d297a098c') 'vauxhall' 'Astra' 2019
 11798 'Manual' 28764 'Petrol' 51.4 1.4 0 0 -1.7933489147566535
 -0.6128336224085622]
Id: 687 | Product: [UUID('ad0812e0-833e-3454-8b96-57087d74d95d') 'audi' 'A1' 2017 12995
 'Manual' 16763 'Petrol' 55.4 1.4 0 0 -1.7796678808977375
 -0.5917232571357975]
Id: 73973 | Product: [UUID('72583cbd-7e1a-399b-b6f2-2f8fb199cddf') 'vauxhall' 'Astra' 2018
 11998 'Manual' 20673 'Petrol' 51.4 1.4 0 0 -1.8168226115407098
 -0.5976657165709207]
Id: 9254 | Product: [UUID('f641fa62-9dd5-3a13-b814-2bd700cff32c') 'audi' 'A1' 2017 12990
 'Manual' 16872 'Petrol' 55.4 1.4 0 0 -1.7800588047128412
 -0.5892544854468167]
Id: 81575 | Product: [UUID('d5e4781f-3a2a-3dbd-9858-7a4e8f373494') 'vauxhall' 'Zafira Tourer'
 2017 11250 'Manual' 22688 'Petrol' 41.5 1.4 0 0 -1.8054992557046678
 -0.5812417806113735]
Id: 81291 | Product: [UUID('fab15bb1-604e-3b50-8bb3-7959b57cc521') 'vauxhall' 'Zafira' 2017
 12232 'Manual' 21505 'Petrol' 41.5 1.4 0 0 -1.8150259205984958
 -0.6112232105084435]
Id: 31916 | Product: [UUID('b6a2d492-db24-36e3-a566-b0f48ad3891c') 'ford' 'Grand C-MAX' 2018
 13647 'Manual' 10652 'Petrol' 47.1 1.0 0 0 -1.8075682214143387
 -0.5802468942307756]
Id: 10445 | Product: [UUID('9e625ae1-be06-3691-a514-bdb1b3ce836a') 'audi' 'A1' 2017 13000
 'Manual' 15811 'Petrol' 55.4 1.4 0 0 -1.7777644388273626
 -0.6121908382267979]

In [18]:
data_merged.to_csv("used_cars.csv", sep=",", index=None)